### ISSUE TITLE
Repo 'Cleaning'

### ISSUE THREAD

**Issue by chrisleaptrott** [CntoDev/cnto-mmt-repo#58]
With the advent of several new additions to our repo and the latest arma and ace updates, we've got a few redundancies in our repo that we can clean up. Some of these are minor and wouldn't require much at all to do (like the hold stamina HUD's removal), but others are more geared to cleaning out maps and things we don't use, such as Sahrani.

This will server to track any of those cleaning tasks so that they can be tested and what-not before being made official.

**Comment by freghar** [comment]
I'm closing this as tec_csat and tryk were removed from the cnto mod repo some time ago.

**Comment by JamesTheClarke** [comment]
Reopening this due to the latest repo update which introduced a redundant mod: **HLC SAW** pbo. This is already a native part of RHS. As long as we have RHS within the repo adding HLC SAW to it is unnecessary (would be like adding ShackTac Map gestures pbo to the stmods folder even though its a native part of ACE3).

In a similar vein I'd like to question the choice of including HLC AWC and M14. Our approach in the past has always been to keep the repo as lean as possible, of course we'd experiment with new mods and see if we feel like they _could_ be used some time in the future, but those which are very clearly not part of our gameplay style won't make it into the selection. AWC features two long range sniper rifles, which we won't use in our official events. Same goes for the M14 marksmen rifles. Even if we want to conduct mini ops where those marksmen and sniper rifles could come into play we already have a great number of such available via vanilla and RHS. To me both HLC AWC and M14 pbos are dead download weight, which should be removed in the next repo update.

**Comment by TRyujin** [comment]
As discussed on forums, we're not going to be opening any new issues or continuing discussions on existing ones in this repo, unless absolutely necessary.

It was the first time for Abuk and me to update the repo, I apologise for making a mistake. We'll be sure to document why certain parts of mods are being used while others aren't so that next time whoever updates the repo knows what (not) to do.
